{
 "title": "Alarm Dashboard",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Customers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failed Pods/Containers",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason",
       "legendFormat": "{{pod}}  | {{container}}  |  {{namespace}}  |  {{reason}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 9 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9.7 },
     "options": {
      "content": "Active Workflow Queues with Ready Messages."
     }
    },
    {
     "title": "Queue(s) with Ready Messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 9.7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_ready{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"} != 0, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\") >= label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_ready{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"} offset 1m != 0, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"))\r\n",
       "legendFormat": "{{queue}}   |   {{vhost}}  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 18.7 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 3, "x": 0, "y": 19.4 },
     "options": {
      "content": "Active Workflow Queues with unacked messages."
     }
    },
    {
     "title": "Queue(s) with Unacked Messages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 19.4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_unacked{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"} > 1, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\") >= label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_unacked{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"} offset 5m > 1, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"))\r\n",
       "legendFormat": "{{queue}}   |   {{vhost}}  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 29.4 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 30.099999999999998 },
     "options": {
      "content": "Active Workflow Queues with No Consumers."
     }
    },
    {
     "title": "Queue(s) with No Consumers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 30.099999999999998 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_consumers{queue=~\"(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.1.1.(.*).In)\"}, \"RC\", \"$1-$2-$3-$4-$5\", \"queue\", \"(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.1.1.(.*).In)\") == 0\r\n\r\n",
       "legendFormat": "{{queue}}   |   {{vhost}}  "
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 3.6 },
     "options": {
      "content": "List of worker nodes with memory consumption >70% and master nodes with memory consumption >60%"
     }
    },
    {
     "title": "Node(s) with high memory consumption",
     "type": "graph",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 3.6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(\r\n  label_replace(kube_node_role{role=\"master\"}, \"role\", \"master\", \"role\", \"master\") *\r\n  on(node) group_left() (\r\n    (\r\n      node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes\r\n    ) * 100 / node_memory_MemTotal_bytes > 60\r\n  )\r\n)\r\nor\r\n(\r\n  label_replace(kube_node_role{role=\"node\"}, \"role\", \"worker\", \"role\", \"node\") *\r\n  on(node) group_left() (\r\n    (\r\n      node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes\r\n    ) * 100 / node_memory_MemTotal_bytes > 70\r\n  )\r\n)\r\n",
       "legendFormat": "{{node}}  |  {{role}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 12.6 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "title": "Node(s) with CPU consumption >15%",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13.299999999999999 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "\r\n(\r\n  label_replace(sum by (kubernetes_io_hostname, kubernetes_io_role) (rate (container_cpu_usage_seconds_total{image!=\"\"}[3m])) * 100, \"kubernetes_io_role\", \"worker\", \"kubernetes_io_role\", \"node\") / \r\n  label_replace(sum by (kubernetes_io_hostname, kubernetes_io_role) (machine_cpu_cores), \"kubernetes_io_role\", \"worker\", \"kubernetes_io_role\", \"node\")\r\n)>15",
       "legendFormat": "{{kubernetes_io_hostname}}  |  {{kubernetes_io_role}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 20.299999999999997 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "title": "Nodes with file-system(Disk) usage >30%",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20.999999999999996 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": " (container_fs_usage_bytes{device=~\"/dev/root\",id=\"/\"}) /  (container_fs_limit_bytes{device=~\"/dev/root\",id=\"/\"}) * 100 >50",
       "legendFormat": "{{kubernetes_io_hostname}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 26.999999999999996 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "title": "Failed Containers",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27.699999999999996 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason",
       "legendFormat": "{{pod}}  | {{container}}  |  {{namespace}}  |  {{reason}}"
      },
      {
       "expr": "kube_pod_status_phase{namespace=\"your-namespace\", label_app=\"your-app\"}\r\n",
       "legendFormat": "{{pod}}  |  {{container}}  |  {{namespace}} |  {{phase}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 33.699999999999996 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 34.4 },
     "options": {
      "content": "Flow container(s) with memory usage >220Mb."
     }
    },
    {
     "title": "Flow Container(s) Memory Usage (>220 MiB)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 34.4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(sum by (pod,container, namespace) (container_memory_working_set_bytes{image!=\"\",pod=~\"(.*)-(........)-(....)-(....)-(....)-(............)-(.....)\"}) ) >230686720",
       "legendFormat": "{{pod}}  |  {{container}}  |  {{namespace}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 42.4 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 43.1 },
     "options": {
      "content": "Memory usage of pods with critically high memory usage.\r\n<p>\r\n<a href=https://robomq.sharepoint.com/:u:/r/sites/OperationsPortal/SitePages/Pods-with-critically-high-memory-Consumtion-Grafan-Dashboard-Panel.aspx?csf=1&web=1&e=CpKdpI target=\"_blank\"> Learn More.... </a>\r\n</p>"
     }
    },
    {
     "title": "Pods with Critically High Memory Consumption",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 43.1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(\r\n(\r\n    sum(container_memory_usage_bytes{container!=\"\"}) by (pod, namespace)\r\n      / on (pod) group_left(container)\r\n    sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod, namespace)\r\n  )\r\n  * sum(kube_pod_info{namespace=~\"default|istio-system|kube-logging|aws-cost-alarm|cluster-balancer\"}) by (pod,namespace) >0.8\r\n) * sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod, namespace)\r\n\r\nor\r\n(\r\n  (\r\n    sum(container_memory_usage_bytes{container!=\"\"}) by (pod, namespace)\r\n      / on (pod) group_left(container)\r\n    sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod, namespace)\r\n    unless\r\n    sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod,namespace)\r\n  )\r\n  * sum(kube_pod_info{namespace=~\"default|istio-system|kube-logging|aws-cost-alarm|cluster-balancer\"}) by (pod,namespace) >1.6\r\n) * sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod, namespace)\r\nor (\r\n  (\r\n    sum(container_memory_usage_bytes{container!=\"\"}) by (pod, namespace)\r\n    unless\r\n    (sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (pod,namespace) and sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod,namespace))\r\n  )\r\n  * sum(kube_pod_info{namespace=~\"default|istio-system|kube-logging|aws-cost-alarm|cluster-balancer\"}) by (pod,namespace)\r\n)>1073741824\r\n\r\n\r\n",
       "legendFormat": "{{pod}}  |  {{namespace}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 51.1 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 51.800000000000004 },
     "options": {
      "content": "Nodes with sum of memory <a href= \"https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits\" target=\"_blank\">requests </a> >85% of total node memory\r\n<p>\r\n<a href=https://robomq.sharepoint.com/sites/OperationsPortal/SitePages/CPU-Memory-Limits-and-Requests-Explanation.aspx target=\"_blank\"> Learn More.... </a>\r\n</p>"
     }
    },
    {
     "title": "Node Allocated Memory ( >85%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 51.800000000000004 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(100 * sum by(node) (kube_pod_container_resource_requests{resource=\"memory\"}), \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\") / on(kubernetes_io_hostname) group_left() sum by(kubernetes_io_hostname, kubernetes_io_role) (machine_memory_bytes) \r\n>85\r\n",
       "legendFormat": " {{ node }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 58.800000000000004 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 59.50000000000001 },
     "options": {
      "content": "Nodes with sum of CPU <a href= \"https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#requests-and-limits\" target=\"_blank\">requests </a> >80% of total node CPU\r\n<p>\r\n<a href=https://robomq.sharepoint.com/sites/OperationsPortal/SitePages/CPU-Memory-Limits-and-Requests-Explanation.aspx target=\"_blank\"> Learn More.... </a>\r\n</p>"
     }
    },
    {
     "title": "Node Allocated CPU ( >80%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 59.50000000000001 },
     "yaxes": [
      { "format": "percent", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "label_replace(100 * sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\"}), \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\") / on (kubernetes_io_hostname) group_left() sum (machine_cpu_cores) by (kubernetes_io_hostname, kubernetes_io_role)\r\n>80",
       "legendFormat": " {{ node }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 66.5 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    }
   ]
  },
  {
   "title": "Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Node(s) with Memory Usage >30%",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4.6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 * (sum by(instance) (rabbitmq_detailed_process_resident_memory_bytes / rabbitmq_detailed_resident_memory_limit_bytes{job=~\"broker(.)+ObjectMetrics\"})) >30",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Broker Node(s) with Disk Usage >25%",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4.6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100-(rabbitmq_detailed_disk_space_available_bytes{job=~\"broker(.)+ObjectMetrics\"} / 1024 / 1024 / 1024 )>25",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 14.6 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 3, "x": 0, "y": 15.299999999999999 },
     "options": {
      "content": "List of all queues across the broker with memory usage >200MiB."
     }
    },
    {
     "title": "Queue Memory Usage (>200 MiB)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 15.299999999999999 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_detailed_queue_messages_ram_bytes{queue!=\"\"}>209715200",
       "legendFormat": "{{queue}}  |  {{vhost}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 25.299999999999997 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 25.999999999999996 },
     "options": {
      "content": "List of all queues across the broker with ready messages >25000."
     }
    },
    {
     "title": "Too Many Ready Messages (>25000)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 21, "x": 3, "y": 25.999999999999996 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_detailed_queue_messages{queue!=\"\"}>25000",
       "legendFormat": "{{queue}}  {Vhost: {{vhost}} }"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 34 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 34.7 },
     "options": {
      "content": "Active Workflow Queues/Business Queues with ready messages."
     }
    },
    {
     "title": "Queue(s) with Ready Messages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 34.7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_ready{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"} != 0, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\") >= label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_ready{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"} offset 1m != 0, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"))\r\n\r\nor\r\n\r\n(rabbitmq_detailed_queue_messages_ready{queue=~\"Hire2Retire.(.*).[iI]n|ifdMessage\"} != 0 >= rabbitmq_detailed_queue_messages_ready{queue=~\"Hire2Retire.(.*).[iI]n|ifdMessage\"} offset 1m != 0)",
       "legendFormat": "{{queue}}   |   {{vhost}}  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 43.7 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 3, "x": 0, "y": 44.400000000000006 },
     "options": {
      "content": "Active Workflow Queues/Business Queues with unacked messages."
     }
    },
    {
     "title": "Queue(s) with Unacked Messages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 44.400000000000006 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_unacked{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"} > 1, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\") >= label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_unacked{queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"} offset 5m > 1, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"))\r\n\r\nor\r\n\r\n(rabbitmq_detailed_queue_messages_unacked{queue=~\"Hire2Retire.(.*).[iI]n|ifdMessage\"} != 0 >= rabbitmq_detailed_queue_messages_unacked{queue=~\"Hire2Retire.(.*).[iI]n\"} offset 1m != 0)",
       "legendFormat": "{{queue}}   |   {{vhost}}  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 54.400000000000006 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 55.10000000000001 },
     "options": {
      "content": "Active Workflow Queues/Business Queues with no consumers."
     }
    },
    {
     "title": "Queue(s) with no consumers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 21, "x": 3, "y": 55.10000000000001 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_consumers{queue=~\"(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.1.1.(.*).In)\"}, \"RC\", \"$1-$2-$3-$4-$5\", \"queue\", \"(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.1.1.(.*).In)\") == 0\r\n\r\nor\r\n\r\n(rabbitmq_detailed_queue_consumers{queue=~\"Hire2Retire.(.*).[iI]n|ifdMessage\"} == 0)",
       "legendFormat": "{{queue}}   |   {{vhost}}  "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 0.7, "w": 24, "x": 0, "y": 62.10000000000001 },
     "options": {
      "content": "<h1 style=\"background-color:Black;\"}>.</h1>"
     }
    }
   ]
  }
 ]
}