{
 "title": "Pod3 Kubernetes cluster monitoring dashboard",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "Pods", "query": { "query": "label_values(pod)" } },
   {
    "name": "Containers",
    "query": {
     "query": "label_values(container_memory_usage_bytes{pod=~\"$Pods$\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Filtered Object(s) Memory usage ÷ Filtered Node(s) Total Memory (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pods$\",container=~\"^$Containers$\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 99.761\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Filtered Object(s) CPU Usage  ÷ Filtered Node(s) Total CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nsum(sum by (kubernetes_io_hostname, kubernetes_io_role) (rate (container_cpu_usage_seconds_total {image!=\"\", kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pods$\",container=~\"^$Containers$\"}[3m])) * 100) / sum(sum by (kubernetes_io_hostname, kubernetes_io_role) (machine_cpu_cores {kubernetes_io_hostname=~\"^$Node$\"}))"
    }
   ]
  },
  {
   "title": "Filtered Object(s) Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"^$Pods$\",container=~\"^$Containers$\",kubernetes_io_hostname=~\"^$Node$\"}) * 0.9997619"
    }
   ]
  },
  {
   "title": "Filtered Node(s) Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) "
    }
   ]
  },
  {
   "title": "Filtered Object(s) Used CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (kubernetes_io_hostname, kubernetes_io_role) (rate (container_cpu_usage_seconds_total {image!=\"\", kubernetes_io_hostname=~\"^$Node$\",pod=~\"^$Pods$\",container=~\"^$Containers$\"}[3m])))"
    }
   ]
  },
  {
   "title": "Filtered Node(s) Total CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Node(s) Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Filtered Node(s) Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "\r\n (node_memory_MemTotal_bytes{node=~\"^$Node$\"} - node_memory_MemFree_bytes{node=~\"^$Node$\"} - node_memory_Buffers_bytes{node=~\"^$Node$\"} - node_memory_Cached_bytes{node=~\"^$Node$\"} - node_memory_SReclaimable_bytes{node=~\"^$Node$\"}) * 100 /  (node_memory_MemTotal_bytes{node=~\"^$Node$\"} )",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Filtered Node(s) Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\r\n  label_replace(kube_node_role{role=\"master\"}, \"role\", \"master\", \"role\", \"master\") *\r\n  on(node) group_left() (\r\n    (\r\n      node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes\r\n    ) \r\n  )\r\n)\r\nor\r\n(\r\n  label_replace(kube_node_role{role=\"node\"}, \"role\", \"worker\", \"role\", \"node\") *\r\n  on(node) group_left() (\r\n    (\r\n      node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes\r\n    ) \r\n  )\r\n)\r\n",
     "legendFormat": "{{node}}  |  {{role}}"
    }
   ]
  },
  {
   "title": "Filtered Node(s) CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(\r\n  label_replace(sum by (kubernetes_io_hostname, kubernetes_io_role) (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}[3m])) * 100, \"kubernetes_io_role\", \"worker\", \"kubernetes_io_role\", \"node\") / \r\n  label_replace(sum by (kubernetes_io_hostname, kubernetes_io_role) (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}), \"kubernetes_io_role\", \"worker\", \"kubernetes_io_role\", \"node\")\r\n)",
     "legendFormat": "{{kubernetes_io_hostname}}  |  {{kubernetes_io_role}}"
    }
   ]
  },
  {
   "title": "Filtered Node(s) filesystem usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " (container_fs_usage_bytes{device=~\"/dev/root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) /  (container_fs_limit_bytes{device=~\"/dev/root\",id=\"/\",kubernetes_io_hostname=~\"^$Node$\"}) * 100",
     "legendFormat": "{{kubernetes_io_hostname}}"
    }
   ]
  },
  {
   "title": "Filtered Object(s) Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Failed Pods/Containers",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{pod=~\"^$Pods$\",container=~\"^$Containers$\"}",
     "legendFormat": "{{pod}}  | {{container}}  |  {{namespace}}  |  {{reason}}"
    },
    {
     "expr": "kube_pod_status_phase{namespace=\"your-namespace\", label_app=\"your-app\"}\r\n",
     "legendFormat": "{{pod}}  |  {{container}}  |  {{namespace}} |  {{phase}}"
    }
   ]
  },
  {
   "title": "Filtered Pod(s) Memory usage (%)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace) (container_memory_usage_bytes{image!=\"\", pod=~\"^$Pods$\", kubernetes_io_hostname=~\"^$Node$\"}) / ignoring (pod, namespace) group_left sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})*100\r\n",
     "legendFormat": "{{pod}}  | {{namespace}}"
    }
   ]
  },
  {
   "title": "Filtered Pod(s) memory usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace) (container_memory_usage_bytes{image!=\"\",pod=~\"^$Pods$\",kubernetes_io_hostname=~\"^$Node$\"}) \r\n\r\n\r\n",
     "legendFormat": "{{ pod }}  | {{ namespace }}"
    }
   ]
  },
  {
   "title": "Filtered Pod(s) CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace, kubernetes_io_hostname)(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"^$Pods$\",  kubernetes_io_hostname=~\"^$Node$\"}[5m])) * 100 / ignoring (pod, namespace, kubernetes_io_hostname)  group_left sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) ",
     "legendFormat": "{{ pod }}  |  {{ namespace }}"
    }
   ]
  },
  {
   "title": "Filtered Container(s) Memory usage (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod,container, namespace) (container_memory_usage_bytes{image!=\"\", pod=~\"^$Pods$\",container=~\"^$Containers$\", kubernetes_io_hostname=~\"^$Node$\"}) / ignoring (pod,container, namespace) group_left sum(machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})*100",
     "legendFormat": "{{ pod }}  |  {{ container }}  |    {{ namespace }}"
    }
   ]
  },
  {
   "title": "Filtered Container(s) memory usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"^$Pods$\",container=~\"^$Containers$\",kubernetes_io_hostname=~\"^$Node$\"}) by (container, pod,namespace)",
     "legendFormat": "{{ pod }}  |  {{ container }}  |    {{ namespace }}"
    }
   ]
  },
  {
   "title": "Filtered Container(s) CPU usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, container, namespace, kubernetes_io_hostname)(rate(container_cpu_usage_seconds_total{image!=\"\",pod=~\"^$Pods$\",container=~\"^$Containers$\", kubernetes_io_hostname=~\"^$Node$\"}[5m])) * 100 / ignoring (pod,container, namespace, kubernetes_io_hostname)  group_left sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) ",
     "legendFormat": "{{ pod }}  |  {{ container }}  |    {{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory usage Distribution by Namespace (%)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 1, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\".*\"}) by (namespace) / ignoring (namespace) group_left sum(container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\".*\"}) * 100\r\n",
     "legendFormat": " {{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU usage Distribution by Namespace (%)",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 11, "x": 12, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\n\r\nsum(container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\".*\"}) by (namespace) / ignoring (namespace) group_left sum(container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\".*\"}) * 100\r\n",
     "legendFormat": " {{ namespace }}"
    }
   ]
  },
  {
   "title": "Node Allocated Memory (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 * sum by(node) (kube_pod_container_resource_requests{resource=\"memory\"}), \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\") / on(kubernetes_io_hostname) group_left() sum by(kubernetes_io_hostname, kubernetes_io_role) (machine_memory_bytes) \r\n",
     "legendFormat": " {{ node }}"
    }
   ]
  },
  {
   "title": "Filtered Object(s) Allocated Memory (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 * sum by(node,pod,container) (kube_pod_container_resource_requests{resource=\"memory\",pod=~\"^$Pods$\",container=~\"^$Containers$\"}), \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\") / on(kubernetes_io_hostname) group_left() sum by(kubernetes_io_hostname, kubernetes_io_role) (machine_memory_bytes) \r\n\r\n\r\n",
     "legendFormat": "{{pod}}  |  {{container}}  |  {{node}} "
    }
   ]
  },
  {
   "title": "Node  Allocated CPU (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "percent", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "label_replace(100 * sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\"}), \"kubernetes_io_hostname\", \"$1\", \"node\", \"(.*)\") / on (kubernetes_io_hostname) group_left() sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node\"}) by (kubernetes_io_hostname, kubernetes_io_role)\r\n",
     "legendFormat": " {{ node }}"
    }
   ]
  }
 ]
}