{
 "title": "RabbitMQ broker monitoring dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "vhost", "query": { "query": "label_values(vhost)" } },
   {
    "name": "queue",
    "query": {
     "query": "label_values(rabbitmq_detailed_queue_messages{vhost=~\"$vhost\"}, queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Memory Usage(%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (sum by(instance) (rabbitmq_detailed_process_resident_memory_bytes / rabbitmq_detailed_resident_memory_limit_bytes{job=~\"broker(.)+ObjectMetrics\"})) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage(%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-(rabbitmq_detailed_disk_space_available_bytes{job=~\"broker(.)+ObjectMetrics\"} / 1024 / 1024 / 1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queue(s) with Memory Consumption",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages_ram_bytes{vhost=~\"$vhost\",queue=~\"$queue\"}>0",
     "legendFormat": "{{queue}}  |  Vhost: {{vhost}}"
    }
   ]
  },
  {
   "title": "Memory Usage Distribution by Vhost(%)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rabbitmq_detailed_queue_messages_ram_bytes{vhost!=\"\"}) by (vhost)/  ignoring (vhost) group_left sum (rabbitmq_detailed_queue_messages_ram_bytes{vhost!=\"\"}) *100 >0.5\r\n\r\n",
     "legendFormat": "{{vhost}}"
    }
   ]
  },
  {
   "title": "Flow Queues Ready Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_ready{vhost=~\"$vhost\",queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"} != 0, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\") >= label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_ready{vhost=~\"$vhost\",queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"} offset 1m != 0, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice)\"))",
     "legendFormat": "{{queue}}   |   {{vhost}}  "
    }
   ]
  },
  {
   "title": "Flow Queues Consumer Down",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_consumers{vhost=~\"$vhost\",queue=~\"(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In)\"}, \"RC\", \"$1-$2-$3-$4-$5\", \"queue\", \"(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In)\") == 0",
     "legendFormat": "{{queue}}   |   {{vhost}}  "
    }
   ]
  },
  {
   "title": "Flow Queues Unacked Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_unacked{vhost=~\"$vhost\",queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"} > 1, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\") >= label_replace(kube_replicationcontroller_status_replicas{replicationcontroller=~\"(.*)-(........)-(....)-(....)-(....)-(............)\"} == 1, \"RC\", \"$2-$3-$4-$5-$6\", \"replicationcontroller\", \"(.*)-(........)-(....)-(....)-(....)-(............)\") * on(RC) group_right() label_replace(rabbitmq_detailed_queue_messages_unacked{vhost=~\"$vhost\",queue=~\"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"} offset 5m > 1, \"RC\", \"$2-$3-$4-$5-$6\", \"queue\", \"(hire2retire.|)(........)-(....)-(....)-(....)-(............)(.1.In|.smtp|.1.1.In|.eventservice|.1.1.JiraWorkManagement.In|.1.1.ServiceNow.In|.1.1.JiraServiceManagement.In|.1.1.JiraSoftware.In)\"))",
     "legendFormat": "{{queue}}   |   {{vhost}}  "
    }
   ]
  },
  {
   "title": "All Queues Across Broker with Ready Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages{vhost=~\"$vhost\",queue=~\"$queue\"}>0",
     "legendFormat": "{{queue}}  {Vhost: {{vhost}} }"
    }
   ]
  },
  {
   "title": "All Queues Across Broker with Unacked Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_messages_unacked{vhost=~\"$vhost\",queue=~\"$queue\"}>0",
     "legendFormat": "{{queue}}  {Vhost: {{vhost}} }"
    }
   ]
  },
  {
   "title": "All Queues Across Broker with No Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_detailed_queue_consumers{vhost=~\"$vhost\",queue=~\"$queue\"}==0",
     "legendFormat": "{{queue}}  {Vhost: {{vhost}} }"
    }
   ]
  },
  {
   "title": "RabbitMQ Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rabbitmq_detailed_connections{job=~\"broker(.)+ObjectMetrics\"})\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}